/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weatherdata;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hasitha Iroshana
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    
    
    
    
    
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2back = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        start2 = new javax.swing.JButton();
        start3 = new javax.swing.JButton();
        start4 = new javax.swing.JButton();
        tempLabel = new javax.swing.JLabel();
        humLabel = new javax.swing.JLabel();
        windLabel = new javax.swing.JLabel();
        rainfallLabel = new javax.swing.JLabel();
        rainingLabel = new javax.swing.JLabel();
        temp2 = new javax.swing.JTextField();
        temp3 = new javax.swing.JTextField();
        temp4 = new javax.swing.JTextField();
        hum2 = new javax.swing.JTextField();
        hum3 = new javax.swing.JTextField();
        hum4 = new javax.swing.JTextField();
        speed2 = new javax.swing.JTextField();
        speed3 = new javax.swing.JTextField();
        speed4 = new javax.swing.JTextField();
        rainFall2 = new javax.swing.JTextField();
        rainFall3 = new javax.swing.JTextField();
        rainFall4 = new javax.swing.JTextField();
        rainning2 = new javax.swing.JTextField();
        rainning3 = new javax.swing.JTextField();
        rainning4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        status2 = new javax.swing.JTextField();
        status3 = new javax.swing.JTextField();
        status4 = new javax.swing.JTextField();
        sleepTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        set = new javax.swing.JButton();
        requestPerMinute = new javax.swing.JLabel();
        location = new javax.swing.JPanel();
        tempValue = new javax.swing.JTextField();
        tempButton = new javax.swing.JLabel();
        humButton = new javax.swing.JLabel();
        hum = new javax.swing.JTextField();
        windButton = new javax.swing.JLabel();
        wind = new javax.swing.JTextField();
        rainfallButton = new javax.swing.JLabel();
        rainFall = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        manual = new javax.swing.JLabel();
        israin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather Monitoring Project Manual Data Send");
        setBackground(new java.awt.Color(0, 51, 51));

        jPanel2back.setBackground(new java.awt.Color(0, 102, 0));
        jPanel2back.setForeground(new java.awt.Color(0, 102, 0));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        start2.setBackground(new java.awt.Color(51, 153, 0));
        start2.setText("Start");
        start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start2ActionPerformed(evt);
            }
        });

        start3.setBackground(new java.awt.Color(51, 153, 0));
        start3.setText("Start");
        start3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start3ActionPerformed(evt);
            }
        });

        start4.setBackground(new java.awt.Color(51, 153, 0));
        start4.setText("Start");
        start4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start4ActionPerformed(evt);
            }
        });

        tempLabel.setText("Temperature");

        humLabel.setText("Humidity");

        windLabel.setText("Wind Speed");

        rainfallLabel.setText("Rain Fall");

        rainingLabel.setText("Raining");

        temp2.setText("temp");

        temp3.setText("temp");

        temp4.setText("temp");

        hum2.setText("hum");
        hum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hum2ActionPerformed(evt);
            }
        });

        hum3.setText("hum");

        hum4.setText("hum");

        speed2.setText("speed");

        speed3.setText("speed");

        speed4.setText("speed");

        rainFall2.setText("rain fall");

        rainFall3.setText("rain fall");

        rainFall4.setText("rain fall");

        rainning2.setText("Y/N");

        rainning3.setText("Y/N");

        rainning4.setText("Y/N");

        jLabel3.setText("Status");

        status2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status2ActionPerformed(evt);
            }
        });

        sleepTime.setText("50000");

        jLabel4.setText("Sleep time");

        set.setText("set");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });

        requestPerMinute.setText("12 updates per minutes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(start4)
                                .addGap(18, 18, 18)
                                .addComponent(temp4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(start3)
                                .addGap(18, 18, 18)
                                .addComponent(temp3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hum3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(hum4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(speed2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speed3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speed4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(start2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(hum2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(tempLabel)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(humLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(windLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sleepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rainFall2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rainFall4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rainFall3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rainning3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(rainning2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rainning4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(rainfallLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rainingLabel)))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(status2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(status3)
                            .addComponent(status4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(set)
                        .addGap(18, 18, 18)
                        .addComponent(requestPerMinute)
                        .addGap(130, 130, 130))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sleepTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(set)
                    .addComponent(requestPerMinute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rainingLabel)
                    .addComponent(rainfallLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(humLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start2)
                    .addComponent(hum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speed2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rainning2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rainFall2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start3)
                    .addComponent(temp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rainFall3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rainning3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speed3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start4)
                    .addComponent(temp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speed4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rainFall4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rainning4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        location.setBackground(new java.awt.Color(153, 153, 153));

        tempValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempValueActionPerformed(evt);
            }
        });

        tempButton.setText("Temperature");

        humButton.setText("Humidity");

        windButton.setText("Wind Speed");

        rainfallButton.setText("Rain Fall");

        send.setBackground(new java.awt.Color(102, 255, 102));
        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        manual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manual.setText("Manual Data Input");

        israin.setText("1");

        jLabel1.setText("Raining");

        jLabel2.setText("Locatin no");

        loc.setText("3");

        javax.swing.GroupLayout locationLayout = new javax.swing.GroupLayout(location);
        location.setLayout(locationLayout);
        locationLayout.setHorizontalGroup(
            locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(locationLayout.createSequentialGroup()
                        .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempButton)
                            .addComponent(tempValue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(locationLayout.createSequentialGroup()
                                .addComponent(humButton)
                                .addGap(18, 18, 18)
                                .addComponent(windButton))
                            .addGroup(locationLayout.createSequentialGroup()
                                .addComponent(hum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(wind, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(locationLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(manual, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rainFall, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rainfallButton))
                .addGap(27, 27, 27)
                .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(locationLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(israin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(locationLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(send))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        locationLayout.setVerticalGroup(
            locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(locationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempButton)
                    .addComponent(humButton)
                    .addComponent(windButton)
                    .addComponent(rainfallButton)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(locationLayout.createSequentialGroup()
                        .addGroup(locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rainFall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(israin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, locationLayout.createSequentialGroup()
                        .addComponent(send)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2backLayout = new javax.swing.GroupLayout(jPanel2back);
        jPanel2back.setLayout(jPanel2backLayout);
        jPanel2backLayout.setHorizontalGroup(
            jPanel2backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2backLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2backLayout.setVerticalGroup(
            jPanel2backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2backLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempValueActionPerformed
    
    int n2=0;
    private void start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start2ActionPerformed
        if(n2==0){
            start2.setBackground(Color.RED);
            start2.setText("Stop");
            n2=1;
            Main.startTread(0);
        }else{
            start2.setBackground(Color.GREEN);
            start2.setText("Start");
            n2=0;
            Main.stop(0);
        }
    }//GEN-LAST:event_start2ActionPerformed
    
    int n3=0;
    private void start3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start3ActionPerformed
        if(n3==0){
            start3.setBackground(Color.RED);
            start3.setText("Stop");
            n3=1;
            Main.startTread(1);
        }else{
            start3.setBackground(Color.GREEN);
            start3.setText("Start");
            n3=0;
            Main.stop(1);
        }
    }//GEN-LAST:event_start3ActionPerformed

    int n4;
    private void start4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start4ActionPerformed
        if(n4==0){
            start4.setBackground(Color.RED);
            start4.setText("Stop");
            n4=1;
            Main.startTread(2);
        }else{
            start4.setBackground(Color.GREEN);
            start4.setText("Start");
            n4=0;
            Main.stop(2);
        }
    }//GEN-LAST:event_start4ActionPerformed

    
    
public void setGuiData(int i, int tmp, int hum, int speed, int israin, int fall){
    switch (i) {
        case 2:
            temp2.setText(Integer.toString(tmp));
            rainFall2.setText(Integer.toString(fall));
            rainning2.setText(Integer.toString(israin));
            hum2.setText(Integer.toString(hum));
            speed2.setText(Integer.toString(speed));
            break;
        case 3:
            temp3.setText(Integer.toString(tmp));
            rainFall3.setText(Integer.toString(fall));
            rainning3.setText(Integer.toString(israin));
            hum3.setText(Integer.toString(hum));
            speed3.setText(Integer.toString(speed));
            break;
        case 4:
            temp4.setText(Integer.toString(tmp));
            rainFall4.setText(Integer.toString(fall));
            rainning4.setText(Integer.toString(israin));
            hum4.setText(Integer.toString(hum));
            speed4.setText(Integer.toString(speed));
            break;
        default:
            break;
    }
}
    
public void setStatus(int i, int status){
    String currentStatus = null;
    if(status==0){
        currentStatus = "error";
    }else if(status==1){
        currentStatus = "sent";
    }else if(status==2){
        currentStatus = "succuss";
    }else if(status==-1){
        currentStatus = "error";
    }else if(status==-2){
        currentStatus = "not sent";
    }
    
    
    if(i==2){
        status2.setText(currentStatus);
    }else if(i==3){
        status3.setText(currentStatus);
    }else if(i==4){
        status4.setText(currentStatus);
    }

}    
    
    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
      
        
      URL url;
        try {
            url = new URL("http://digitalthings.comlu.com/weather/dataset1.php?temp="+tempValue.getText()+
                    "&hum="+hum.getText()+"&wind_speed="+wind.getText()+"&current_rainfall="+rainFall.getText()
                    +"&location="+loc.getText()+"&is_raining="+israin.getText());
        System.out.println(url);
        HttpURLConnection conn;
        
        conn = (HttpURLConnection) url.openConnection();
       
        conn.setRequestMethod("GET");
        
        
        BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
        String line;
        line = rd.readLine();
        
        rd.close();
        
        System.out.println(line);  
        
        } catch (MalformedURLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ProtocolException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
        
        
        
    }//GEN-LAST:event_sendActionPerformed

    public int getSleepTime(){
        return interval;
    }    
    
    
    
    
    
    
    
    private void status2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status2ActionPerformed

    private void hum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hum2ActionPerformed

    
    private int interval =5000;
    
    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
        interval = Integer.parseInt(sleepTime.getText());
        int rpm;
        rpm = 60000/interval;
        requestPerMinute.setText(Integer.toString(rpm)+" updates per minute");
    }//GEN-LAST:event_setActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hum;
    private javax.swing.JTextField hum2;
    private javax.swing.JTextField hum3;
    private javax.swing.JTextField hum4;
    private javax.swing.JLabel humButton;
    private javax.swing.JLabel humLabel;
    private javax.swing.JTextField israin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2back;
    private javax.swing.JTextField loc;
    private javax.swing.JPanel location;
    private javax.swing.JLabel manual;
    private javax.swing.JTextField rainFall;
    private javax.swing.JTextField rainFall2;
    private javax.swing.JTextField rainFall3;
    private javax.swing.JTextField rainFall4;
    private javax.swing.JLabel rainfallButton;
    private javax.swing.JLabel rainfallLabel;
    private javax.swing.JLabel rainingLabel;
    private javax.swing.JTextField rainning2;
    private javax.swing.JTextField rainning3;
    private javax.swing.JTextField rainning4;
    private javax.swing.JLabel requestPerMinute;
    private javax.swing.JButton send;
    private javax.swing.JButton set;
    private javax.swing.JTextField sleepTime;
    private javax.swing.JTextField speed2;
    private javax.swing.JTextField speed3;
    private javax.swing.JTextField speed4;
    private javax.swing.JButton start2;
    private javax.swing.JButton start3;
    private javax.swing.JButton start4;
    private javax.swing.JTextField status2;
    private javax.swing.JTextField status3;
    private javax.swing.JTextField status4;
    private javax.swing.JTextField temp2;
    private javax.swing.JTextField temp3;
    private javax.swing.JTextField temp4;
    private javax.swing.JLabel tempButton;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JTextField tempValue;
    private javax.swing.JTextField wind;
    private javax.swing.JLabel windButton;
    private javax.swing.JLabel windLabel;
    // End of variables declaration//GEN-END:variables
}


